# 1. Import the libraries we need
from google import genai
from dotenv import load_dotenv
import os
import math


# 2. Load the API key from the .env file and create the Gemini client
load_dotenv()

client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)


# 3. Create our small knowledge base (documents we want to search)
documents = [
    "Python is widely used in machine learning and AI development.",
    "React is a JavaScript library used to build user interfaces.",
    "AWS provides cloud services such as EC2, S3 and Lambda.",
    "RAG allows LLM applications to retrieve relevant external information."
]


# 4. Convert a piece of text into an embedding vector
def get_embedding(text):
    response = client.models.embed_content(
        model="gemini-embedding-001",
        contents=text
    )

    return response.embeddings[0].values


# 5. Calculate how similar two embedding vectors are
def cosine_similarity(vector1, vector2):
    dot_product = sum(a * b for a, b in zip(vector1, vector2))

    magnitude1 = math.sqrt(sum(a * a for a in vector1))
    magnitude2 = math.sqrt(sum(b * b for b in vector2))

    return dot_product / (magnitude1 * magnitude2)


# 6. Create and store an embedding for every document
document_embeddings = []

for document in documents:
    embedding = get_embedding(document)
    document_embeddings.append(embedding)


# 7. Get the user's question and convert it into an embedding
question = input("Ask a question: ")

question_embedding = get_embedding(question)


# 8. Compare the question with every document and store the similarity scores
results = []

for document, embedding in zip(documents, document_embeddings):

    similarity = cosine_similarity(
        question_embedding,
        embedding
    )

    results.append((document, similarity))


# 9. Sort documents from most similar to least similar
results.sort(
    key=lambda x: x[1],
    reverse=True
)


# 10. Take the top 2 most relevant documents
top_results = results[:2]


# 11. Extract the text from those relevant documents
context = "\n".join(
    document for document, similarity in top_results
)


# 12. Give the question + retrieved context to Gemini
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=f"""
Answer the user's question using the context below.

Context:
{context}

Question:
{question}
"""
)


# 13. Display the final answer generated by Gemini
print("\nAnswer:")
print(response.text)